version: '3.1'

services:
  app:
    networks:
      - backend
    depends_on:
      - 'db'
    build: '.'
    volumes:
      - .:/ewallet
    ports:
      - "80:80"
  db:
    image: 'postgres:9.6-alpine'
    networks:
      - backend
    environment:
      POSTGRES_USER: 'mdd'
      POSTGRES_PASSWORD: 'MDD2019implementationreference'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
networks:
  backend: